apiVersion: v1
kind: Service
metadata:
  name: postgrs-service
  namespace: default
spec:
  type: cluserIP
  selector:
    app: postgrs-app
  ports:
    - protocol: TCP
    - port: 80
      targetPort: 80
