pipeline {

    agent any
    options {
        timestamps()
        ansiColor('xterm')
         
    }
    
    environment {
        IMAGE_NAME= 'vote-app'
        REGION_NAME= 'asia-south1'
    }
    stages {
        stage ("checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/Gopidesi19/voting-app.git'
                sh 'ls -ltr'
                echo "cloned succesfully"
            }
        
        }
        stage ("Build") {
            steps {
                echo "Build stage completed"
            }
        }
        stage ("test") {
            steps {
                echo "test stage completed"
            }
        }
        stage('SonarQube Scan') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'

                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=vote \
                        -Dsonar.projectName=vote \
                        -Dsonar.sources=. \
                        -Dsonar.python.version=3.11
                        """
                    }
                }
             }
        }
        stage ("docker image") {
            steps {
                sh 'docker --version'
                sh 'ls -ltr'
                sh 'cd vote'
                sh 'docker build -t ${IMAGE_NAME}:1.9 vote/.'
                sh 'docker images'
                echo "docker images featched successfully"
            }
        }
        stage ("docker login") {
            steps {
                withCredientials([
                    usernamePassword (
                        credientialsId: 'dockerhub-creds', \
                        usernameVariable: 'DOCKER_USER',\
                        usernamePassword: 'DOCKER_PASS'
                    )
                ])
                {
                 sh " echo $DOCKER_PASS | docker login -u $DOKER_USER --password-standin "
                }
            }
        }
        stage ("docker push") {
            steps {
                sh 'docker tag ${IMAGE_NAME}:1.9 devops119/${IMAGE_NAME}:1.9'
                sh 'docker push devops119/${IMAGE_NAME}:1.9'
                echo "image pushed to docker Hub successfully"
            }
        }
        stage ("authentication with GKE") {
            steps {
                sh '''
                    gcloud container cluster get-credentials voting-cluster --region {REGION_NAME}
                '''
            }
        }
        stage ("Deploy to GKE") {
            steps {
                sh 'kubectl apply -f k8s-specifications/vote/*'
            }
        }
    }
}
