pipeline {

    agent any
    options {
        timestamps()
        ansiColor('xterm')

    }
    tools {
        sonarQube 'sonar-scaner'
    }
    environment {
        IMAGE_NAME= 'worker-app'
        REGION_NAME= 'asia-south1'
    }
    stages {
        stage ("checkout") {
            steps {
                git branch: 'main', URL: 'https://github.com/Gopidesi19/voting-app.git'
                sh 'ls -ltr'
                echo "cloned succesfully"
            }

        }
        stage ("Build") {
            steps {
                sh '''
                    dotnet restore  # downlods all nuget packages
                    dotnet build    # compile the c# code
                    dotnet publish  # create deployment ready file
                '''
                echo "Build stage completed"
            }
        }
        stage ("test") {
            steps {
                echo "test stage completed"
            }
        }
        stage ('sonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarQube')
                {
                    sh '''
                        sonar-scaner \
                        -Dsonar.projectKey=worker \
                        -Dsonar.projectName=worker \
                        -Dsonar.sources=. \
                     '''
                    }
             }
         }
        stage ("docker image") {
            steps {
                sh 'docker --version'
                sh 'docker build -t ${IMAGE_NAME}:1.9 .'
                sh 'docker rmi ${IMAGE_NAME}'
                sh 'docker images'
                echo "docker images featched successfully"
            }
        }
        stage ("docker login") {
            steps {
                withCredentials([
                    usernamePassword (
                        credentialsId: 'dockerhub-creds'
                        usernameVariables: 'DOCKER_USER'
                        usernamePassword: 'DOCKER_PASS'
                    )
                ])
                {
                 sh " echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-standin "
                }
            }
        }
        stage ("docker push") {
            steps {
                sh 'docker tag ${IMAGE_NAME}:1.9 devops119/${IMAGE_NAME}:1.9
                sh 'docker push devops119/${IMAGE_NAME}:1.9'
                echo "image pushed to docker Hub successfully"
            }
        }
        stage ("authentication with GKE") {
            steps {
                sh '''
                    gcloud container cluster get-credentials voting-cluster --region ${REGION_NAME}
                '''
            }
        }
        stage ("Deploy to GKE") {
            steps {
                sh 'kubectl apply -f k8s-specifications/worker/*'
            }
        }
    }
}
